name: playground
on: push

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ github }}

  bar:
    if: github.ref == 'refs/heads/master'
    needs: foo
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ github }}
