name: playground
on: push

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
    - run: test ${{ github.ref }} = /refs/heads/master && echo 'top' || echo 'flop'

  bar:
    if: github.ref == 'refs/heads/master'
    needs: foo
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ github.ref }}
