name: playground
on: push

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ github.ref }} == '/ref/head/master'

  bar:
    if: github.ref == 'refs/heads/master'
    needs: foo
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ github.ref }}
